version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-2004:current
    resource_class: arm.medium
    working_directory: ~/project
    steps:
      - run:
          name: Get Source Code
          command: git clone https://github.com/neovim/neovim ~/project
      - run:
          name: APT update
          command: sudo apt-get update
      - run:
          name: Install dependencies
          command: sudo apt-get install -y ninja-build gettext libtool libtool-bin autoconf automake cmake g++ pkg-config unzip curl doxygen
      - run:
          name: build
          command: |
            make CMAKE_BUILD_TYPE=Release CMAKE_EXTRA_FLAGS="-DCMAKE_INSTALL_PREFIX:PATH="
            make DESTDIR="./build/release/nvim-arm64" install
            cd ./build
            cpack -C Release
      - store_artifacts:
          path: ./nvim-linux64.tar.gz
          destination: nvim-arm64.tar.gz
      - store_artifacts:
          path: ./nvim-linux64.deb
          destination: nvim-arm64.deb
            
