version: 2.1

workflows:
  test-env-vars:
    jobs:
      - build-alacritty-arm64:
          context: github
          
jobs:
  build-alacritty-arm64:
    machine:
      image: ubuntu-2004:current
    resource_class: arm.medium
    working_directory:  ~/project
    steps:
      - run:
          name: get dependencies
          command: |
            sudo apt install git curl cmake pkg-config libfreetype6-dev libfontconfig1-dev libxcb-xfixes0-dev libxkbcommon-dev python3
      - run:
          name: install rustup.rs
          command: |
            curl --proto '=https' --tlsv1.2 -sDf https://sh.rustup.rs | sh -s -- -y
            source ~/.cargo/env
            rustup override set stable
            rustup update stable
      - run:
          name: get source code
          command: |
            cd ~/project
            git clone https://github.com/alacritty/alacritty
      - run:
          name: build
          command: |
            cd ~/project/alacritty
            cargo build --release --no-default-features --features=x11
      - store_artifacts:
          path: ~/project/alacritty/target/release/alacritty
          destination: alacritty-arm64

  create-init-arm64-archlinux-image:
    machine:
      image: ubuntu-2004:current
    resource_class: arm.medium
    working_directory: ~/project
    steps:
      - run:
          name: Get arm archlinux rootfs
          command: |
            mkdir rootfs
            curl -L http://os.archlinuxarm.org/os/ArchLinuxARM-aarch64-latest.tar.gz -o archlinux.tar.gz
            sudo tar xzf archlinux.tar.gz -C rootfs
            sudo tar cf archlinux.tar -C rootfs .
            docker import archlinux.tar archlinuxarm64:latest
      - store_artifacts:
          path: ~/project/archlinux.tar
          destination: archlinux-arm64.tar

  build:
    machine:
      image: ubuntu-2004:current
    resource_class: arm.medium
    working_directory: ~/project
    steps:
      - run:
          name: Get Source Code
          command: git clone https://github.com/neovim/neovim ~/project
      - run:
          name: APT update
          command: sudo apt-get update
      - run:
          name: Install dependencies
          command: sudo apt-get install -y ninja-build gettext libtool libtool-bin autoconf automake cmake g++ pkg-config unzip curl doxygen
      - run:
          name: build
          command: |
            make CMAKE_BUILD_TYPE=Release CMAKE_EXTRA_FLAGS="-DCMAKE_INSTALL_PREFIX:PATH="
            make DESTDIR="./build/release/nvim-arm64" install
            cd ./build
            cpack -C Release -D CPACK_PACKAGE_FILE_NAME="nvim-arm64"
            ls -l
      - store_artifacts:
          path: ~/project/build/nvim-arm64.tar.gz
          destination: nvim-arm64.tar.gz
      - store_artifacts:
          path: ~/project/build/nvim-arm64.deb
          destination: nvim-arm64.deb
      - run:
          name: make a release on github
          command: |
            cd ~/project
            mkdir githubrelease
            cp ./build/nvim-arm64.tar.gz ./githubrelease/nvim-arm64.tar.gz
            cp ./build/nvim-arm64.deb ./githubrelease/nvim-arm64.deb
            go install github.com/tcnksm/ghr@latest
            VERSION=0.8.0
            ls -l ./githubrelease/
            echo "-t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -delete ${VERSION} ./githubrelease/"
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -delete 0.8.0 ./githubrelease/
