version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-2004:current
    working_directory: ~/project
    steps:
      - run:
          name: Get Source Code
          command: git clone https://github.com/neovim/neovim ~/project
      - run:
          name: APT update
          command: sudo apt-get update
      - run:
          name: Install dependencies
          command: sudo apt-get install -y ninja-build gettext libtool libtool-bin autoconf automake cmake g++ pkg-config unzip curl doxygen
      - run:
          name: build
          command: |
            make CMAKE_BUILD_TYPE=Release
            ls -l ./build
            make DESTDIR="./build/release/nvim-arm64" install
            ls -l ./build
            cd ./build
            cpack -C Release
            ls -l
      - run:
          name: test
          command: make unittest
      - run:
          name: check
          command: |
            ls -l ~/project/build
            ls -l ./build
            
